"""add query to reports

Revision ID: 36df2108e8c1
Revises: 59a6f3707e08
Create Date: 2026-08-20 22:59:48.679302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36df2108e8c1'
down_revision: Union[str, Sequence[str], None] = '59a6f3707e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'reports',
        sa.Column(
            'query',
            sa.String(length=5000),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE reports SET query = 'SELECT 1' WHERE query IS NULL"
    )

    op.alter_column(
        'reports',
        'query',
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'query')
    # ### end Alembic commands ###
