"""add completed at to report runs

Revision ID: 598731dae745
Revises: 3b6936f9ba27
Create Date: 2026-08-16 22:03:21.883720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598731dae745'
down_revision: Union[str, Sequence[str], None] = '3b6936f9ba27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_runs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_runs', 'completed_at')
    # ### end Alembic commands ###
