"""add error message to report runs

Revision ID: 59a6f3707e08
Revises: 598731dae745
Create Date: 2026-08-16 22:35:28.978355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a6f3707e08'
down_revision: Union[str, Sequence[str], None] = '598731dae745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_runs', sa.Column('error_message', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_runs', 'error_message')
    # ### end Alembic commands ###
